[firebase]
type = "service_account"
project_id = "excelgraph-67ab7"
private_key_id = "273c1033947fe895d3e655e21743824ff88c4918"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDAx1hkvVg8Mzk5
kUpQoy3TAcuteQSPJoEGzSY2R+UxoncQJbiSdwat7ExF2RONOo9Rfk2vqPfufvYF
gMe2I4gRmVl2PEne+UnYqdGt1agdpTYKA9JexRV8UXh5KYC+pi9fxcf4Ul9wLOcS
hqDX3klbBYR+zT8Y/a6AsXUNBpO8RoCGGYU7iHnAQgbyepDfpke0YWfVosp0bY1o
q2HEkYBIqgVSxaX0XX6qzv2v4apBTZnk0Qp/YaBw33qYgo0S5jHDDIIZzzpAp39/
j6oiQveDLQxLRNXTeYs19Y0Txj3rdXKRocHxd552b9zQ72lA6MHghGhDOrM8M1Wu
q2VhHXqvAgMBAAECggEAUbuzBHMq18s39epdwbaNlSrrug7XGgJPLh0ImHb++35Q
UK5NhPul/1NyOyMAIR606O5N7a4MADggAtFI2zZRWHTV80U4ZKr43j2RwswVTQxg
zvoz1S5mH6FDHMu15B79cvOeBvCVui+vgLFHvH5oR4kdVc2bdPMJa1LRt8YUGPxl
4C/8MBTHae3rZ/wk3SxYt0OFtf00Yakvdza99vN3DA5868DYB7xiJbxCDGzPXN2l
fTg89UUA4LTYiCvpg/TLGnqbjHcnzopa5l7i87AaL2tvPeUhQLHKsRpfFISBtHXo
PVLe8F0XxU5yzvJzM5agtR/qosQSGwwayVsF0NFuMQKBgQD2GnJKpwGWwth12gVG
g4yMbnxcY6HSj2ew7ifk1c05iPvSyMsAzqHePWOaFstawbz9+Eocc18CJqPICWpT
eonTwlpXuKKV6i7DylM2/BNeORYXplGa/bZwvidKpyQJVsTpMy71NxECrdbvcQ3a
MNuXIY4Vd1hA/xcoZviEvKhSbQKBgQDIh/Bz1LKZXot6TYMoZ+tQ6ykC4akD2HEJ
v7jJABMRe2Vd4EEcNuJcP4Pl+lpcmkFyA5TI9XTcjlJjOSrk2knD2lpc4HoWEbh+
hm9GxdLlYISt/BX4wk//mAYgh50ni1nVT9NxzNhyTT+AjYyE2qJrVVErIt6pKG78
v+Dgt7OwCwKBgQCozJTt3US6umQr2WFa7ym8vJ9x4yiAOro9YexdCcRcnTdUaULM
B+6Ad4zUiKPsWQwfCmkSwJM+72/Q6ZxTK65TX3AF0O87ckenJSQUh6tlKjSb/gjl
DPZQuCxNCP0vpqMi7Gdd6+ov8zqEOv/sUyyaqXpCAPy4f/7LSG1W5etxtQKBgQCl
wmDLjo0XY+SNc1cwZj5IxCpBXIFWUWqW8WjwlWQttj+DSuTnSqLwN/xydPCOzV+9
vCIXv3Ya/nYx2MaRJ7OD9pFtZozkgz9rLvr6mHmM66yhGNicqRpxn5uo9hC86F6Y
igSxc++TBDGytM7r3sIVUQ/oRUmisG6V9JIRjyg0IwKBgQCTsRqPsEd7s4gaxMAM
x2O2TL4EEwL9WkGMam/1w1Eha7vkD5kcrVW93QcKwiEp2sSKxqVEBWwOfv0YNIYu
9nTFBMxOigkuhtuqLn/7cMoqgxSsqaOSn3x2/DcrQjA0EOlSKZXfYKcn4S20u3Ak
+X2TLniYvgSHLc13u2ADzLHPVQ==
-----END PRIVATE KEY-----
"""
client_email = "firebase-adminsdk-euuqj@excelgraph-67ab7.iam.gserviceaccount.com"
client_id = "107623851957748005159"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-euuqj%40excelgraph-67ab7.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
